apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: messages
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
      - name: messages
        image: {{.Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
        env:
        - name: CONNECTION
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: connection
---
apiVersion: v1
kind: Service
metadata:
  name: messages
spec:
  type: LoadBalancer
  loadBalancerIP: {{.Values.ip}}
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: messages